apiVersion: v1
kind: Service
metadata:
  name: fastfood-payment-app
spec:
  selector:
    app: fastfood-payment-app
  ports:
    - protocol: TCP
      port: 8000
      nodePort: 32100
      targetPort: 8000
  type: NodePort